set_property IOSTANDARD LVCMOS33 [get_ports {ans[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[0]}]

# set_property IOSTANDARD LVCMOS33 [get_ports {res[31]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[30]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[29]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[28]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[27]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[26]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[25]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[24]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[23]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[22]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[21]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[20]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[19]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[18]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[17]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[16]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[15]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[14]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {res[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN J15 [get_ports {ins[0]}]
set_property PACKAGE_PIN L16 [get_ports {ins[1]}]
set_property PACKAGE_PIN M13 [get_ports {ins[2]}]
set_property PACKAGE_PIN N17 [get_ports reset]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN R15 [get_ports {ins[3]}]
set_property PACKAGE_PIN R17 [get_ports {ins[4]}]
set_property PACKAGE_PIN T18 [get_ports {ins[5]}]
set_property PACKAGE_PIN U18 [get_ports {ins[6]}]
set_property PACKAGE_PIN R13 [get_ports {ins[7]}]
set_property PACKAGE_PIN L18 [get_ports {seg[0]}]
set_property PACKAGE_PIN T11 [get_ports {seg[1]}]
set_property PACKAGE_PIN P15 [get_ports {seg[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN K16 [get_ports {seg[4]}]
set_property PACKAGE_PIN R10 [get_ports {seg[5]}]
set_property PACKAGE_PIN T10 [get_ports {seg[6]}]
set_property PACKAGE_PIN J17 [get_ports {ans[0]}]
set_property PACKAGE_PIN J18 [get_ports {ans[1]}]
set_property PACKAGE_PIN T9 [get_ports {ans[2]}]
set_property PACKAGE_PIN J14 [get_ports {ans[3]}]
set_property PACKAGE_PIN P14 [get_ports {ans[4]}]
set_property PACKAGE_PIN T14 [get_ports {ans[5]}]
set_property PACKAGE_PIN K2 [get_ports {ans[6]}]
set_property PACKAGE_PIN U13 [get_ports {ans[7]}]
